@echo off
echo Building...
call npm run build
echo Staging changes...
git add .
echo Committing...
git commit -m "update"
echo Pushing to GitHub...
git push
echo Done! Live in 2-3 minutes at snamburi1980.github.io/dumont-inventory
