@echo off
echo Building...
call npm run build
echo Staging changes...
git add .
echo Committing...
git commit -m "update"
echo Pushing to GitHub dev branch...
git push origin dev
echo Done! Pushed to dev branch.